version: "3.9"
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
      image: mysql:5.7.22
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: "root"
        MYSQL_DATABASE: "ambassador"
        MYSQL_USER: "root"
        MYSQL_PASSWORD: "root"
      volumes:
        - ./dbdata:/var/lib/mysql
      ports:
        - "33066:3306"


